"""
Core models — Career data, resume history, roadmaps, saved items,
interview progress, courses, AI chat history, and learning analytics.
"""

import uuid
from django.db import models
from django.conf import settings


class CareerRecommendation(models.Model):
    """AI-generated career recommendations for users."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='career_recommendations',
    )
    title = models.CharField(max_length=200)
    description = models.TextField()
    match_score = models.PositiveIntegerField(default=0)  # 0-100
    required_skills = models.JSONField(default=list)
    salary_range = models.CharField(max_length=100, blank=True, default='')
    growth_outlook = models.CharField(max_length=50, blank=True, default='')
    is_favorite = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-match_score', '-created_at']

    def __str__(self):
        return f'{self.title} ({self.match_score}%)'


class ResumeAnalysis(models.Model):
    """History of resume analyses performed by the user."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='resume_analyses',
    )
    resume_text = models.TextField()
    skills_found = models.JSONField(default=list)
    missing_skills = models.JSONField(default=list)
    improvements = models.JSONField(default=list)
    roles_suggested = models.JSONField(default=list)
    ats_tips = models.JSONField(default=list)
    overall_score = models.PositiveIntegerField(default=0)  # 0-100
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name_plural = 'Resume Analyses'

    def __str__(self):
        return f'Analysis #{self.pk} — Score: {self.overall_score}'


class SavedRoadmap(models.Model):
    """Saved career roadmaps generated by the AI."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='saved_roadmaps',
    )
    goal = models.CharField(max_length=200)
    skills = models.TextField(blank=True, default='')
    weeks_data = models.JSONField(default=list)
    progress = models.PositiveIntegerField(default=0)  # 0-100
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.goal} — {self.progress}%'


class InterviewSession(models.Model):
    """Records of mock interview sessions."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='interview_sessions',
    )
    role = models.CharField(max_length=200)
    questions = models.JSONField(default=list)
    answers = models.JSONField(default=list)
    score = models.PositiveIntegerField(default=0)  # 0-100
    completed = models.BooleanField(default=False)
    duration_seconds = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.role} — {"Done" if self.completed else "In Progress"}'


class SavedCourse(models.Model):
    """Courses bookmarked by the user."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='saved_courses',
    )
    title = models.CharField(max_length=300)
    platform = models.CharField(max_length=100)
    url = models.URLField()
    description = models.TextField(blank=True, default='')
    category = models.CharField(max_length=100, blank=True, default='')
    progress = models.PositiveIntegerField(default=0)  # 0-100
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f'{self.title} ({self.platform})'


class UserNote(models.Model):
    """User notes and bookmarks."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='notes',
    )
    title = models.CharField(max_length=200)
    content = models.TextField()
    tags = models.JSONField(default=list, blank=True)
    is_pinned = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-is_pinned', '-updated_at']

    def __str__(self):
        return self.title


class ChatMessage(models.Model):
    """AI chat conversation history."""

    ROLE_CHOICES = [
        ('user', 'User'),
        ('assistant', 'Assistant'),
    ]

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='chat_messages',
    )
    session_id = models.UUIDField(default=uuid.uuid4)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f'{self.role}: {self.content[:50]}'


class CareerProgress(models.Model):
    """Track user's overall career development progress."""

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='career_progress',
    )
    resumes_analyzed = models.PositiveIntegerField(default=0)
    roadmaps_created = models.PositiveIntegerField(default=0)
    interviews_completed = models.PositiveIntegerField(default=0)
    courses_completed = models.PositiveIntegerField(default=0)
    code_executions = models.PositiveIntegerField(default=0)
    skills_count = models.PositiveIntegerField(default=0)
    overall_score = models.PositiveIntegerField(default=0)  # 0-100
    weekly_goal = models.PositiveIntegerField(default=5)  # hours
    weekly_progress = models.FloatField(default=0)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Career Progress'

    def __str__(self):
        return f'{self.user.username} — Score: {self.overall_score}'


class RecentlyViewedCareer(models.Model):
    """Tracks recently viewed career paths."""

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
        related_name='recently_viewed',
    )
    career_title = models.CharField(max_length=200)
    career_data = models.JSONField(default=dict)
    viewed_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-viewed_at']

    def __str__(self):
        return f'{self.career_title}'
